### ISSUE TITLE
v2_0_4_4.tar contains 2.4.0.3 version file

### ISSUE THREAD

**Issue by mpbraendle** [pkp/pln#88]
Both the v2_0_4_4.tar release package as well as the package available in the plugin gallyery contain 2.4.0.3 version file.

**Comment by jonasraoni** [comment]
That's true, were you able to install anyway or it failed?

**Comment by mpbraendle** [comment]
Yes, I was able to install it. I changed version and date in version.xml manually.

**Comment by jonasraoni** [comment]
@asmecher is it ok to edit the release with a new `.tar.gz` and update the md5 hash on the `plugins.xml` or do you think it's better to release a new version (2.0.4-5)?

**Comment by asmecher** [comment]
@jonasraoni, would folks who installed the plugin via the old `.tar.gz` have the `2.4.0-4` version incorrectly in their database after trying to install the plugin? Or would the install fail, or leave the `2.4.0-3` version active?

If the `2.4.0-4` version is incorrectly installed in the database, I'd suggest releasing a new 2.4.0-5. Otherwise updating the tarball should be fine.

**Comment by jonasraoni** [comment]
The version is taken from the `version.xml`, so I guess the installation will keep the 2.4.0-3 and a 2.4.0-4 codebase. Anyway, I'll create a new tar.gz with the updated `version.xml` and include some new translations.

**Comment by jonasraoni** [comment]
This issue should be fixed by:
- https://github.com/pkp/plugin-gallery/pull/275
